### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by gdjsky01** [leogps/ItunesLibraryParser#1]
I was looking forward to using this library. But at least two classes are missing (maybe more).
CopyTrackFailureInformation
FileCopyException

Perhaps you could add these? And do a clean build to make sure nothing else is missing. Thanks! :)

**Comment by leogps** [comment]
Will look into it. 

Thanks,
P.

**Comment by leogps** [comment]
Sorry, My gitignore file was messed up. I have checked in the missing files and I also have some outstanding features that I've been meaning to check in. It should compile now.

Thanks,
Paul.

**Comment by gdjsky01** [comment]
Thank you. My use case is to try and get a CSV of all the Audiobooks (only). iTunes' XML is so terrible in that it thinks it needs to list every track as a separate entry. That is fine for Albums. But Audiobooks are or are not, regardless of 'tracks'.  :) :+1:  thanks

This should make creating a groovy script a lot easier.
